### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [elliebirbeck/model-deployment-flask#1]
Hello, 

please when i run  python api.py , i get this error : 

Traceback (most recent call last):
  File "api.py", line 44, in <module>
    model = joblib.load('model.pkl')
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 567, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'

Any help please . Thanks

**Comment by elliebirbeck** [comment]
If you run 'python model.py' it will generate a file 'model.pkl' for you 👍

**Comment by ikrambennasrbennasr** [comment]
@elliebirbeck Thank you it runs :)

**Comment by Issamshani17** [comment]
thank you

**Comment by Sadia1803** [comment]
> If you run 'python model.py' it will generate a file 'model.pkl' for you 👍

hey, where I have to run this?

**Comment by varaprasad1016** [comment]
> > If you run 'python model.py' it will generate a file 'model.pkl' for you 👍
> 
> hey, where I have to run this?

In the same directory where you are currently working.
