### ISSUE TITLE
no 'extra_32x32.mat'

### ISSUE THREAD

**Issue by fanhaito** [elliebirbeck/model-deployment-flask#4]
Running model shows no data.where is from extra_32x32.mat?

Error prompt:"FileNotFoundError: [Errno 2] No such file or directory: 'extra_32x32.mat'"

**Comment by chasingkarma-zz** [comment]
I downloaded the file from http://ufldl.stanford.edu/housenumbers/ and moved it to over the working the directory.

**Comment by fanhaito** [comment]
Thanks. I get the data from  http://ufldl.stanford.edu/housenumbers/
