### ISSUE TITLE
I dont have a *.pkl model, but just have a *.pth model(pytorch).

### ISSUE THREAD

**Issue by bemoregt** [elliebirbeck/model-deployment-flask#5]
Hi, @elliebirbeck 

I dont have a *.pkl model, but just have a *.pth model(pytorch).

Is my *.pth model also works in your code?

Thanks in advance~.

**Comment by elliebirbeck** [comment]
yep that will also work. the pkl library is just used to serialise the model, but any method of saving/loading the model can be used. you will need to replace the functions specific to joblib / pickle / scikitlearn with the pytorch equivalents.

e.g.
joblib.load('model.pkl') > torch.load('model.pth')
model.predict(img) > model.forward(img) 
etc
